name: Build Static Dinit (Ubuntu 26.04 static)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:26.04

    steps:
      - name: Install CA certificates & dependencies
        run: |
          apt update -y
          apt install -y --no-install-recommends ca-certificates git build-essential libcap-dev libc-dev
          update-ca-certificates

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: davmac314/dinit
          ref: master

      - name: Build static dinit
        run: |
          ./configure LDFLAGS="-static"
          make -j$(nproc)

      - name: Verify static binary
        run: |
          ldd dinit || echo "✅ 静态编译成功"
          ./dinit --version

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dinit-static-ubuntu26.04-amd64
          path: dinit
